version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: photograf_name
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: photograf
      MYSQL_DATABASE: photograf
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
volumes:
  mysql_data:

networks:
  app_network:
